# TensorFlow Fundamentals

Part 1: Theoretical Questions

1. What are the different data structures used in Tensorflow?. Give some examples.

In TensorFlow, various data structures are used to represent and manipulate tensors, which are multi-dimensional arrays of data. Some of the key data structures in TensorFlow include:

1. **tf.Tensor:**
   - This is the primary data structure in TensorFlow, representing a multi-dimensional array of data.
   - Examples: Scalars (single values), vectors (1D arrays), matrices (2D arrays), and higher-dimensional arrays.

2. **tf.Variable:**
   - It is a special type of tensor that is mutable and can be modified during training.
   - Examples: Model parameters such as weights and biases in neural networks.

3. **tf.Constant:**
   - Represents tensors whose values cannot be changed once assigned.
   - Examples: Constants defined in the graph for fixed values like hyperparameters.

4. **tf.placeholder:**
   - Used for feeding input data into the computational graph during execution.
   - Examples: Placeholders for input features and labels in machine learning models.

5. **tf.RaggedTensor:**
   - Represents tensors with non-uniform shapes, where the lengths of dimensions can vary.
   - Examples: Text data with variable-length sequences of words or sentences.

6. **tf.TensorArray:**
   - A dynamic array-like data structure that can hold tensors of varying shapes and sizes.
   - Examples: Used for dynamic sequence processing tasks, such as sequence generation in recurrent neural networks.

These data structures provide flexibility and efficiency in representing different types of data in TensorFlow, enabling the construction and execution of complex computational graphs for machine learning and deep learning tasks.

In [1]:
import tensorflow as tf

In [2]:
variable=tf.Variable(42)
constant=tf.constant(42)


print(variable)
print(constant)


# Define indices and values for the sparse tensor
indices = tf.constant([[0, 1], [1, 2], [2, 3]],dtype=tf.int64)
values = tf.constant([4, 5, 6],dtype=tf.int64)

# Create a sparse tensor from indices and values
sparse_tensor = tf.sparse.SparseTensor(indices=indices, values=values, dense_shape=[3, 4])
print(sparse_tensor)

ragged=tf.ragged.constant([[2.3],[2,34,4],[4,4]])
print(ragged)

# Define the size of the tensor array
array_size = 5

# Create a tensor array and populate it with a sequence of numbers
tensor_array = tf.TensorArray(dtype=tf.float32, size=array_size)
for i in range(array_size):
    tensor_array = tensor_array.write(i, tf.cast(i, tf.float32))

# Read the values from the tensor array
array = tensor_array.stack()
print(array)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>
tf.Tensor(42, shape=(), dtype=int32)
SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([4 5 6], shape=(3,), dtype=int64), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
<tf.RaggedTensor [[2.3], [2.0, 34.0, 4.0], [4.0, 4.0]]>
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)


### 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

In TensorFlow, both constants and variables are used to store data, but they have different characteristics and usage:

1. **TensorFlow Constant:**
   - A TensorFlow constant is a fixed tensor whose value cannot be changed during the execution of a TensorFlow program.
   - Constants are typically used to represent fixed values such as hyperparameters or input data that do not change over time.
   - Once created, the value of a constant tensor remains the same throughout the execution of the program.
   
2. **TensorFlow Variable:**
   - A TensorFlow variable is a mutable tensor whose value can be modified during the execution of a TensorFlow program.
   - Variables are often used to represent model parameters such as weights and biases in neural networks that need to be updated during training.
   - Unlike constants, the value of a variable tensor can be changed using operations like assignment (`assign`).

Here's an example to illustrate the difference between a TensorFlow constant and a TensorFlow variable:

The constant tensor retains its initial value throughout the execution of the program, while the variable tensor can be updated dynamically using operations like assignment.

In [3]:
constant=tf.constant(42)
variable=tf.Variable(42)
variable.assign(32)
print(f'constant: {constant.numpy()}, variable: {variable.numpy()}')


constant: 42, variable: 32


### 3. Describe the process of matrix addition, multiplication, and element wise operations in TensorFlow.

**Matrix Addition:**

Matrix addition involves adding corresponding elements of two matrices to produce a new matrix of the same shape.

This operation is performed element-wise, meaning that each element in the resulting matrix is the sum of the corresponding elements from the input matrices.

In TensorFlow, matrix addition can be performed using the tf.add() function or the + operator.

**Matrix Multiplication:**

Matrix multiplication involves multiplying corresponding elements of rows and columns from two matrices and summing the results to produce a new matrix.

The dimensions of the matrices must satisfy the matrix multiplication rule, where the number of columns in the first matrix must match the number of rows in the second matrix.

In TensorFlow, matrix multiplication can be performed using the tf.matmul() function.

**Element-wise Operations:**

Element-wise operations involve performing operations independently on each element of a tensor.

These operations are applied to corresponding elements of tensors of the same shape.

Common element-wise operations include addition, subtraction, multiplication, division, exponentiation, etc.

In TensorFlow, element-wise operations can be performed using functions like tf.add(), tf.subtract(), tf.multiply(), tf.divide(), etc., or directly using operators like +, -, *, /.


In [4]:

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result_add = tf.add(matrix1, matrix2)

## Perform matrix multiplication
result_mul=tf.matmul(matrix1,matrix2)

## Perform element-wise Operations
result_opr=tf.multiply(matrix1,5)

## Printing results

print(result_add)
print(result_mul)
print(result_opr)



tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 10]
 [15 20]], shape=(2, 2), dtype=int32)


Part 2: Practical Implementation

Task1 : Creating and Manipulating Matrix

To Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix.

In [7]:
Matrix_a=tf.random.normal(shape=(2,2))
Matrix_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.9529164 , 0.23898947],
       [0.622337  , 0.00435616]], dtype=float32)>

Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix B.

In [10]:
Matrix_b=tf.random.truncated_normal(shape=(2,2))
Matrix_b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.2663774 ,  0.39508513],
       [ 0.525047  ,  0.4040896 ]], dtype=float32)>

3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values
of matrix C.

In [12]:
matrix_c=tf.random.normal(shape=(2,2),mean=2,stddev=0.50)
matrix_c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.8877661, 2.7647822],
       [1.214938 , 2.4416306]], dtype=float32)>

Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [18]:
matrix_d=tf.add(Matrix_a,Matrix_b)
matrix_d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.68653893, 0.63407457],
       [1.1473839 , 0.40844578]], dtype=float32)>

Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [21]:
matrix_e=tf.multiply(matrix_c,matrix_d)
matrix_e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2960249, 1.7530781],
       [1.3940004, 0.9972737]], dtype=float32)>

Task2: Performing Additional Matrix Operation

Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
function.

In [22]:
matrix_f=tf.random.uniform(shape=(2,2))
matrix_f

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.75154185, 0.21117282],
       [0.9258902 , 0.33642912]], dtype=float32)>

Calculate the transpose of matrix F and store the result in matrix G.

In [27]:
matrix_g=tf.transpose(matrix_f)
matrix_g

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.75154185, 0.9258902 ],
       [0.21117282, 0.33642912]], dtype=float32)>

Calculate the elementwise exponential of matrix F and store the result in matrix H.

In [29]:
matrix_h=tf.exp(matrix_f)
matrix_h

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.1202667, 1.2351258],
       [2.5241141, 1.3999397]], dtype=float32)>

Create a matrix I by concatenating matrix F and matrix G horizontally.

In [41]:
matrix_i=tf.concat([matrix_f.numpy(), matrix_g.numpy()],axis=1)

In [42]:
matrix_i

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.75154185, 0.21117282, 0.75154185, 0.9258902 ],
       [0.9258902 , 0.33642912, 0.21117282, 0.33642912]], dtype=float32)>

Create a matrix J by concatenating matrix F and matrix H vertically.

In [46]:
matrix_j=tf.concat([matrix_f.numpy(),matrix_h.numpy()],axis=0)

In [47]:
matrix_j

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.75154185, 0.21117282],
       [0.9258902 , 0.33642912],
       [2.1202667 , 1.2351258 ],
       [2.5241141 , 1.3999397 ]], dtype=float32)>

## The End